base_url = "https://aadi.net.in"
compile_sass = false
build_search_index = false

title = "aadi."
description = "aadi's personal site <3"

generate_feed = true
feed_filename = atom.xml

[markdown]
highlight_code = true

[extra]
render_emoji = true

